### ISSUE TITLE
启动后模拟器错误

### ISSUE THREAD

**Issue by purgeyao** [wuba/Taro-Mortgage-Calculator#12]
![image](https://user-images.githubusercontent.com/36881032/108043772-779d8680-707c-11eb-8a79-805be2a50720.png)

发现Taro-Mortgage-Calculator 后端有下面错误

```
Error: Unable to resolve module `./index` from ``: 

None of these files exist:
  * index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * index/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Volumes/CodeFile/小程序/Taro-Mortgage-Calculator/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Volumes/CodeFile/小程序/Taro-Mortgage-Calculator/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Volumes/CodeFile/小程序/Taro-Mortgage-Calculator/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at /Volumes/CodeFile/小程序/Taro-Mortgage-Calculator/node_modules/metro/src/lib/transformHelpers.js:267:42
    at Server.<anonymous> (/Volumes/CodeFile/小程序/Taro-Mortgage-Calculator/node_modules/metro/src/Server.js:841:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Volumes/CodeFile/小程序/Taro-Mortgage-Calculator/node_modules/metro/src/Server.js:99:24)
    at _next (/Volumes/CodeFile/小程序/Taro-Mortgage-Calculator/node_modules/metro/src/Server.js:119:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)


```

**Comment by qiuziz** [comment]
我这边没有复现 麻烦提供下taro info的信息
